apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment3-django-deploy
  labels:
    app: assignment3-django-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: assignment3-django-deploy
  template:
    metadata:
      labels:
        pod: assignment3-django-deploy
    spec:
      containers:
        - name: assignment3-django-deploy
          image: nyuappsec/assign3:v0
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                 secretKeyRef:
                  name: assignment3-django-secrets
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_DB
              valueFrom:
                 secretKeyRef:
                  name: assignment3-django-secrets
                  key: MYSQL_DB

            - name: MYSQL_HOST
              value: mysql-service

            - name: ALLOWED_HOSTS
              value: "*,"

            - name: MYSQL_USERNAME
              valueFrom:
                 secretKeyRef:
                  name: assignment3-django-secrets
                  key: MYSQL_USERNAME
              
            - name: SECRET_KEY
              valueFrom:
                 secretKeyRef:
                  name: assignment3-django-secrets
                  key: SECRET_KEY

          volumeMounts:
            - name: mysql-volume-mount
              mountPath: /var/lib/busybox

            - name: static-data-volume-mount
              mountPath: /vol/static

      volumes:
        - name: mysql-volume-mount
          persistentVolumeClaim:
            claimName: mysql-pvc

        - name: static-data-volume-mount
          persistentVolumeClaim:
            claimName: static-data-pvc
