# Homework 2 Part 1: Github Action to run tests
name: 'tests'
on:
  push:
    paths:
      - 'AppSec-Project-2/**'
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Upgrade pip
        run: |
          cd AppSec-Project-2
          python -m pip install --upgrade pip
      - name: Install requirements
        run: |
          cd AppSec-Project-2
          pip install -r requirements.txt
      - name: Make migrations
        run: |
          cd AppSec-Project-2
          python manage.py makemigrations LegacySite
      - name: Migrate database
        run: |
          cd AppSec-Project-2
          python manage.py migrate
      - name: Import DBs
        run: |
          cd AppSec-Project-2
          bash import_dbs.sh
      - name: Run tests
        run: |
          cd AppSec-Project-2
          python manage.py test