# Homework 1 Part 2: Github Action to execute make and make tests
name: 'make'
on:
  push:
    paths:
      - 'AppSec-Project-1/**'
jobs:
  make_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: execute make
        run: |
          cd AppSec-Project-1
          make
      - name: execute make test
        run: |
          cd AppSec-Project-1
          make test