# Homework 1 Part 1: Setting up your Environment
name: 'Hello World'
on:
  push:
    paths:
      - 'AppSec-Project-1/**'
jobs:
  hello_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo Hello World
        run: |
          cd AppSec-Project-1
          echo "Hello World"